name: CI
  ​
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

  strategy:
    matrix:
      node-version: [14.5.0]

  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start
